### ISSUE TITLE
Problem installing cython with specific version

### ISSUE THREAD

**Issue by mdavezac** [UCL/GreatCMakeCookOff#21]
came up on bempp/bempp#232.
Possibly because not parsing string right when calling pip from python?

**Comment by jenshnielsen** [comment]
Could it be an old outdated version of pip or setuptools?

**Comment by mdavezac** [comment]
No, I think it's the `==0.21` that's throwing cmake a spanner, rather than anything wrong with pip or package version.

**Comment by jenshnielsen** [comment]
BTW the development branch of bempp now works with 0.23 and 0.22 so we could get rid of ```==0.21```
