### ISSUE TITLE
FindNumpy doesn't set NUMPY_FOUND on success

### ISSUE THREAD

**Issue by fredRos** [UCL/GreatCMakeCookOff#57]
I tried
```cmake
find_package(Numpy)
if(NUMPY_FOUND)
  message("Found numpy")
else()
  message(FATAL_ERROR "Could not find numpy")
endif()
```

and from the output generated by `FindNumpy.cmake` I saw that it found `numpy` but `NUMPY_FOUND` is not set to true. So I went to

```cmake
find_package(Numpy)
if(NUMPY_INCLUDE_DIRS)
  message("Found numpy")
else()
  message(FATAL_ERROR "Could not find numpy")
endif()
```

and that worked. 

Is there perhaps another reason for you to consider numpy wasn't found? If so, the debug output doesn't allude to that.

**Comment by mdavezac** [comment]
You're quite right. Should work now. I think...

**Comment by fredRos** [comment]
Thanks a lot, it works now
